#include "SheetRenderer.h"
#include "../core/DocumentEngine.h"
#include "../core/GeometryLayer.h"
#include "../core/ViewportSystem.h"
#include "SheetCanvas.h"

#include <QPainter>
#include <QPageSize>
#include <QDebug>

SheetRenderer::SheetRenderer(std::shared_ptr<DocumentEngine> engine)
    : engine_(engine)
{
}

bool SheetRenderer::renderSheet(const QString& sheetName, const QString& outputPath) {
    if (!engine_) {
        qWarning() << "No document engine set";
        return false;
    }

    // Create a PDF writer
    QPdfWriter pdfWriter(outputPath);
    pdfWriter.setPageSize(QPageSize(QPageSize::A3));
    pdfWriter.setResolution(300);

    QPainter painter(&pdfWriter);
    if (!painter.isActive()) {
        qWarning() << "Failed to create painter for PDF";
        return false;
    }

    drawSheetContent(painter, sheetName);
    painter.end();

    qDebug() << "Sheet exported to" << outputPath;
    return true;
}

bool SheetRenderer::renderAllSheets(const QString& outputDir) {
    if (!engine_) {
        qWarning() << "No document engine set";
        return false;
    }

    // Placeholder for rendering all sheets
    auto sheets = engine_->allSheets();
    int sheetNum = 1;
    for (const auto& sheet : sheets) {
        QString outputPath = outputDir + "/" + sheet->name() + ".pdf";
        if (!renderSheet(sheet->name(), outputPath)) {
            return false;
        }
        sheetNum++;
    }
    return true;
}

bool SheetRenderer::renderToPdf(const QString& outputPath) {
    if (!engine_) {
        qWarning() << "No document engine set";
        return false;
    }

    QPdfWriter pdfWriter(outputPath);
    pdfWriter.setPageSize(QPageSize(QPageSize::A3));
    pdfWriter.setResolution(300);

    QPainter painter(&pdfWriter);
    if (!painter.isActive()) {
        qWarning() << "Failed to create painter for PDF";
        return false;
    }

    auto sheets = engine_->allSheets();
    bool firstPage = true;

    for (const auto& sheet : sheets) {
        if (!firstPage) {
            pdfWriter.newPage();
        }
        drawSheetContent(painter, sheet->name());
        firstPage = false;
    }

    painter.end();
    qDebug() << "Document exported to" << outputPath;
    return true;
}

void SheetRenderer::drawSheetContent(QPainter& painter, const QString& sheetName) {
    // Paper dimensions (A3 in mm)
    double paperWidth = 297.0;
    double paperHeight = 420.0;
    double mmToPixel = 72.0 / 25.4;  // Convert mm to pixels at 72 DPI

    // Draw paper background
    painter.fillRect(0, 0, paperWidth * mmToPixel, paperHeight * mmToPixel, Qt::white);
    painter.drawRect(0, 0, paperWidth * mmToPixel, paperHeight * mmToPixel);

    // Draw title
    painter.setFont(QFont("Arial", 24, QFont::Bold));
    painter.drawText(20, 40, sheetName);

    // Draw page info
    painter.setFont(QFont("Arial", 10));
    painter.drawText(20, paperHeight * mmToPixel - 20, QString("Generated by SUPaper v0.1"));
}
